### ISSUE TITLE
firmware_installer

### ISSUE THREAD

**Issue by zhl017** [ROBOTIS-GIT/ROBOTIS-OP2#1]
Hey,
Where can I download latest version MX-28.hex files for my op2 use ?

**Comment by ROBOTIS-zerom** [comment]
The file in the link below is the latest version of MX-28 firmware for OP2 firmware installer. 
https://sourceforge.net/p/darwinop/code/HEAD/tree/trunk/robotisop2/Linux/project/firmware_installer/

If you want to download the latest firmware (version 40), please update the firmware using Dynamixel Wizard (Windows).

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
