### ISSUE TITLE
Possible mistake in op2 link data

### ISSUE THREAD

**Issue by ridethepig** [ROBOTIS-GIT/ROBOTIS-OP2#11]
Hello, our team is trying to upgrade framework for our ancient OP2. When studying the code, we found the hardcoded parameters quite different from what we measured. Is there anything wrong with these position parameters?

I guess they are for OP3, rather than OP2. Is this right?

https://github.com/ROBOTIS-GIT/ROBOTIS-OP2/blob/9e18ae6e1b3cc9a770a0823872300274e520caf9/op2_kinematics_dynamics/src/op2_kinematics_dynamics.cpp#L348

```cpp
op2_link_data_[13]->relative_position_ = robotis_framework::getTransitionXYZ(0.000, 0.000, -0.110); 
// just like this one, we think this should be (0.0, 0.0, -93.0)
```

Thank you for your time.

**Comment by ROBOTIS-Will** [comment]
Hi @ridethepig

The actual length of the link of the z axis is -0.093 (in meters) as you correctly measured.
It seems those links are back ported and left unchanged from the source code of OP3.
https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/blob/master/op3_kinematics_dynamics/src/op3_kinematics_dynamics.cpp#L334

Unfortunately, the OP2 is discontinued, therefore, further internal test will not be performed to fix this discrepancy.
Thank you.

**Comment by ridethepig** [comment]
That's really unfortunate.  
Well, we have to try fixing these by ourselves.
