### ISSUE TITLE
wireless adapter not found

### ISSUE THREAD

**Issue by polofh** [ROBOTIS-GIT/ROBOTIS-OP2#2]
Hello, 

we have a problem with our OP2, the wireless adapter is not found on the OS. Is it a hardware or a software problem ? What can i do ?

You can find some log files in attached file.

Thanks in advance for your support. 

Best regards, 

Paul

File : 
[faultyRobot.zip](https://github.com/ROBOTIS-GIT/ROBOTIS-OP2/files/2351757/faultyRobot.zip)

**Comment by ROBOTIS-Will** [comment]
Hi @polofh,

It seems like the wifi card is not being detected in the system.
If possible, please take out the wifi adapter and reconnect to the SBC.
For this, you'll need to disassemble the robot.
Or else you can also request repair service via [ROBOTIS repair center](http://en.robotis.com/model/page.php?co_id=repaircenter).
Thank you.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
